In [46]:
import pandas as pd
import matplotlib as mpl
import plotly.express as px

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/kau2779/Analise-de-Dados-iniciante/refs/heads/main/daily_gym_attendance_workout_data.csv")

In [6]:
df.head()

,member_id,visit_date,age,gender,membership_type,workout_type,workout_duration_minutes,calories_burned,check_in_time,attendance_status
0,1,2024-10-11,64,Other,Annual,HIIT,28,171,20:04,Absent
1,2,2024-06-01,65,Female,Quarterly,Strength Training,72,650,19:17,Absent
2,3,2024-06-13,45,Male,Quarterly,Cardio,70,633,7:24,Absent
3,4,2024-02-05,35,Female,Monthly,CrossFit,64,362,7:18,Absent
4,5,2024-07-13,26,Female,Quarterly,Yoga,31,262,11:22,Absent

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   member_id                 2600 non-null   int64
 1   visit_date                2600 non-null   str
 2   age                       2600 non-null   int64
 3   gender                    2600 non-null   str
 4   membership_type           2600 non-null   str
 5   workout_type              2600 non-null   str
 6   workout_duration_minutes  2600 non-null   int64
 7   calories_burned           2600 non-null   int64
 8   check_in_time             2600 non-null   str
 9   attendance_status         2600 non-null   str
dtypes: int64(4), str(6)
memory usage: 203.3 KB

In [8]:
df.describe()

         member_id          age  workout_duration_minutes  calories_burned
count  2600.000000  2600.000000               2600.000000      2600.000000
mean   1300.500000    41.947308                 70.162692       523.775385
std     750.699674    13.862067                 28.610264       240.449717
min       1.000000    18.000000                 20.000000       102.000000
25%     650.750000    30.000000                 46.000000       329.000000
50%    1300.500000    42.000000                 70.000000       504.000000
75%    1950.250000    54.000000                 94.000000       691.250000
max    2600.000000    65.000000                120.000000      1186.000000

In [9]:
Linhas, Colunas = df.shape[0], df.shape[1]
print(f"Linhas: {Linhas}\nColunas: {Colunas}")

Linhas: 2600
Colunas: 10

In [10]:
df.columns

Index(['member_id', 'visit_date', 'age', 'gender', 'membership_type',
       'workout_type', 'workout_duration_minutes', 'calories_burned',
       'check_in_time', 'attendance_status'],
      dtype='str')

In [15]:
new_columns_name = {
    'member_id' : 'ID_de_Membro',
    'visit_date' : 'Data_da_Visita',
    'age' : 'Idade', 
    'gender' : 'Genêro', 
    'membership_type' : 'Tipo_Cartão_Membro',
    'workout_type' : 'Tipo_Treino',
    'workout_duration_minutes': 'Tempo_duração_Treino',
    'calories_burned' : 'Calorias_Queimadas',
    'check_in_time' : 'Horário_Entrada',
    'attendance_status' : 'Status_Presença'
}
df.rename(columns = new_columns_name, inplace = True)

df.columns

Index(['ID_de_Membro', 'Data_da_Visita', 'Idade', 'Genêro',
       'Tipo_Cartão_Membro', 'Tipo_Treino', 'Tempo_duração_Treino',
       'Calorias_Queimadas', 'Horário_Entrada', 'Status_Presença'],
      dtype='str')

In [22]:
df["Genêro"].value_counts()

Genêro
Female    886
Other     863
Male      851
Name: count, dtype: int64

In [23]:
df["Tipo_Cartão_Membro"].value_counts()

Tipo_Cartão_Membro
Annual       903
Monthly      856
Quarterly    841
Name: count, dtype: int64

In [30]:
df["Tipo_Treino"].value_counts()

Tipo_Treino
Strength Training    559
Cardio               545
HIIT                 520
CrossFit             509
Yoga                 467
Name: count, dtype: int64

In [25]:
df["Status_Presença"].value_counts()

Status_Presença
Absent     1350
Present    1250
Name: count, dtype: int64

In [ ]:
mapeamento_genero = {
    "Female" : "Mulher", 
    "Other" : "Outro",
    "Male" : "Homem"
}

df["Genêro"] = df["Genêro"].replace(mapeamento_genero)

In [ ]:
mapeamento_Tipo_Cartão_Membro = {
    "Annual" : "Anual",
    "Monthly" : "Mensal",
    "Quarterly" : "Trimestal"
}

df["Tipo_Cartão_Membro"] = df["Tipo_Cartão_Membro"].replace(mapeamento_Tipo_Cartão_Membro)

In [ ]:
mapeamento_Tipo_Treino = {
    "Strength Training" : "Treino_Força",
    "Cardio" : "Cardio",        
    "HIIT" : "HIIT",      
    "CrossFit" : "CrosFit",
    "Yoga" : "Yoga"
}

df["Tipo_Treino"] = df["Tipo_Treino"].replace(mapeamento_Tipo_Treino)

In [33]:
mapeamento_Status_Presença = {
    "Absent" : "Falta",
    "Present" : "Presente"
}

df["Status_Presença"] = df["Status_Presença"].replace(mapeamento_Status_Presença)

In [34]:
df.head()

,ID_de_Membro,Data_da_Visita,Idade,Genêro,Tipo_Cartão_Membro,Tipo_Treino,Tempo_duração_Treino,Calorias_Queimadas,Horário_Entrada,Status_Presença
0,1,2024-10-11,64,Outro,Anual,HIIT,28,171,20:04,Falta
1,2,2024-06-01,65,Mulher,Trimestal,Treino_Força,72,650,19:17,Falta
2,3,2024-06-13,45,Homem,Trimestal,Cardio,70,633,7:24,Falta
3,4,2024-02-05,35,Mulher,Mensal,CrosFit,64,362,7:18,Falta
4,5,2024-07-13,26,Mulher,Trimestal,Yoga,31,262,11:22,Falta

In [37]:
df.describe()

       ID_de_Membro        Idade  Tempo_duração_Treino  Calorias_Queimadas
count   2600.000000  2600.000000           2600.000000         2600.000000
mean    1300.500000    41.947308             70.162692          523.775385
std      750.699674    13.862067             28.610264          240.449717
min        1.000000    18.000000             20.000000          102.000000
25%      650.750000    30.000000             46.000000          329.000000
50%     1300.500000    42.000000             70.000000          504.000000
75%     1950.250000    54.000000             94.000000          691.250000
max     2600.000000    65.000000            120.000000         1186.000000

In [40]:
df.isnull()

,ID_de_Membro,Data_da_Visita,Idade,Genêro,Tipo_Cartão_Membro,Tipo_Treino,Tempo_duração_Treino,Calorias_Queimadas,Horário_Entrada,Status_Presença
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
2595,False,False,False,False,False,False,False,False,False,False
2596,False,False,False,False,False,False,False,False,False,False
2597,False,False,False,False,False,False,False,False,False,False
2598,False,False,False,False,False,False,False,False,False,False
2599,False,False,False,False,False,False,False,False,False,False

In [43]:
df.isnull().sum()

ID_de_Membro            0
Data_da_Visita          0
Idade                   0
Genêro                  0
Tipo_Cartão_Membro      0
Tipo_Treino             0
Tempo_duração_Treino    0
Calorias_Queimadas      0
Horário_Entrada         0
Status_Presença         0
dtype: int64

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID_de_Membro          2600 non-null   int64
 1   Data_da_Visita        2600 non-null   str
 2   Idade                 2600 non-null   int64
 3   Genêro                2600 non-null   str
 4   Tipo_Cartão_Membro    2600 non-null   str
 5   Tipo_Treino           2600 non-null   str
 6   Tempo_duração_Treino  2600 non-null   int64
 7   Calorias_Queimadas    2600 non-null   int64
 8   Horário_Entrada       2600 non-null   str
 9   Status_Presença       2600 non-null   str
dtypes: int64(4), str(6)
memory usage: 203.3 KB

In [ ]:
#Contar a quantidade de Genêros
genero_contagem = df["Genêro"].value_counts().reset_index()
genero_contagem.columns = ["tipo_genero", "quantidade"]

#Criar Gráfico
Graf_piz = px.pie(
   genero_contagem,
   names = "tipo_genero",
   values = "quantidade",
   title = "Proporção de gênero na academia",
   hole = 0.5
)

Graf_piz.update_traces(textinfo = "percent + label")

In [ ]:
#Contar a idade
idade_contagem = df["Idade"].value_counts().reset_index()
idade_contagem.columns = ["Idade", "quantidade"]
#Criar o gáfico
Graf_bar = px.bar(
   idade_contagem,
   x = "Idade",
   y =  "quantidade",
   labels = {"quantidade" : "Somatória das pessoas com idades iguas"},
   title = "Idade dentro da Academia"
)
Graf_bar.update_traces(texttemplate = "%{y}", textangle = 0)
Graf_bar.show()

In [90]:
#Contar o tipo de treino e as pessoas
treino_contagem = df["Tipo_Treino"].value_counts().reset_index()
treino_contagem.columns = ["Tipo de Treino", "Quantidade de pessoas"]

#Criar o gáfico
Graf_bar2 = px.bar(
    treino_contagem,
    x = "Tipo de Treino",
    y = "Quantidade de pessoas",
    title = "Modalidades de treinos na academia"
)

Graf_bar2.update_traces(texttemplate = "%{y}", textangle = 0)
Graf_bar2.show()

In [92]:
#Contagem de Presença
presenca_contagem = df["Status_Presença"].value_counts().reset_index()
presenca_contagem.columns  = ["Presença", "Quantidade"]

#Criar Gráfico
Graf_piz2 = px.pie(
    presenca_contagem,
    names = "Presença",
    values = "Quantidade",
    title = "Quantidade de Presenças na Academia",
    hole = 0.5
)

Graf_piz2.update_traces(textinfo = "percent + label")